Assignment T05 done
sathya-git-tech/Training pull request #7
Opened 2023-08-10 09:34 UTC by sathya-git-tech

2023-08-10 16:30 UTC, asfar-nazar requested changes

2023-08-10 16:30 UTC, asfar-nazar commented on Program.cs
> +         for (int i = 2; i < n; i++) {
Do we need to check all numbers till n ?

2023-08-10 16:30 UTC, asfar-nazar commented on Program.cs
> +         int result = 0;
Can you try to do this without using this local variable?

2023-08-14 05:17 UTC, sathya-git-tech commented on Program.cs
> +         for (int i = 2; i < n; i++) {
yes snr

2023-08-14 05:31 UTC, asfar-nazar commented on Program.cs
> +         for (int i = 2; i < n; i++) {
https://en.m.wikipedia.org/wiki/Primality_test

2023-08-14 07:52 UTC, asfar-nazar commented on Program.cs
> +         for (int i = 2; i < n; i++) {
![image](https://github.com/sathya-git-tech/Training/assets/86363064/e04e3787-ab51-4463-8954-5fa492d793f4)

2023-08-17 08:43 UTC, asfar-nazar requested changes

2023-08-17 08:43 UTC, asfar-nazar commented on Program.cs
> +               Console.WriteLine ("is not prime");
Console.WriteLine ($"{n} is not prime");

2023-08-17 08:53 UTC, asfar-nazar approved these changes

2023-10-09 10:18 UTC, closed without merging